@tool
extends EditorScript
# Run from the script editor: File > Run (Ctrl+Shift+X)
# Regenerates the TextKeys registry from the CSV and reports problems in the Output panel

#Pour que la recherche couvre les scènes et le CSV
#Par défaut, « Find in Files » (Ctrl+Shift+F) et « Replace in Files » (Ctrl+Shift+R) ne cherchent que dans les .gd et .gdshader. Dans Project Settings, active « Advanced Settings », puis dans Editor > Script > Search In File Extensions, ajoute tscn et csv.
#Pour renommer une clé, fais alors un « Replace in Files » de l'ancienne clé vers la nouvelle (CSV, scripts et scènes d'un coup), puis relance le générateur.


const CSV_PATH: String = "res://Texts/texts.csv"
const OUTPUT_PATH: String = "res://Scripts/UI/TEXTS/text_keys.gd"
const CSV_DELIMITER: String = ";"

func _run() -> void:
	var file: FileAccess = FileAccess.open(CSV_PATH, FileAccess.READ)
	if file == null:
		push_error("TextKeys: cannot open " + CSV_PATH)
		return
	var header: PackedStringArray = file.get_csv_line(CSV_DELIMITER)
	var keys: PackedStringArray = PackedStringArray()
	var seen_keys: Dictionary[String, bool] = {}
	var problem_count: int = 0
	while not file.eof_reached():
		var row: PackedStringArray = file.get_csv_line(CSV_DELIMITER)
		var key: String = row[0].strip_edges()
		if key.is_empty():
			continue
		if not key.is_valid_identifier():
			push_warning("TextKeys: invalid key (letters, digits, _ only): " + key)
			problem_count += 1
			continue
		if seen_keys.has(key):
			push_warning("TextKeys: duplicate key: " + key)
			problem_count += 1
			continue
		seen_keys[key] = true
		keys.append(key)
		# Every language column must be filled
		for column_index: int in range(1, header.size()):
			if column_index >= row.size() or row[column_index].strip_edges().is_empty():
				push_warning("TextKeys: missing '" + header[column_index] + "' text for " + key)
				problem_count += 1
	file.close()
	# Alphabetical order groups keys by prefix in autocompletion and dropdowns
	keys.sort()
	var lines: PackedStringArray = PackedStringArray()
	lines.append("# GENERATED by res://tools/generate_text_keys.gd from texts.csv. Do not edit by hand.")
	lines.append("class_name TextKeys")
	lines.append("extends RefCounted")
	lines.append("")
	for key: String in keys:
		lines.append("const %s: StringName = &\"%s\"" % [key, key])
	lines.append("")
	lines.append("# All keys, semicolon-separated: used as hint for inspector dropdowns")
	lines.append("const KEY_LIST: String = \"%s\"" % ",".join(keys))
	var output: FileAccess = FileAccess.open(OUTPUT_PATH, FileAccess.WRITE)
	if output == null:
		push_error("TextKeys: cannot write " + OUTPUT_PATH)
		return
	output.store_string("\n".join(lines) + "\n")
	output.close()
	EditorInterface.get_resource_filesystem().scan()
	print("TextKeys: %d keys generated, %d problem(s)" % [keys.size(), problem_count])
