# GENERATED by res://tools/generate_text_keys.gd from texts.csv. Do not edit by hand.
class_name TextKeys
extends RefCounted

const BUTTON_CONTINUE: StringName = &"BUTTON_CONTINUE"
const BUTTON_OK: StringName = &"BUTTON_OK"
const BUTTON_WTF: StringName = &"BUTTON_WTF"
const CAR_VOICE_WELCOME_0: StringName = &"CAR_VOICE_WELCOME_0"
const CAR_VOICE_WELCOME_1: StringName = &"CAR_VOICE_WELCOME_1"
const CAR_VOICE_WELCOME_2: StringName = &"CAR_VOICE_WELCOME_2"
const CAR_VOICE_WELCOME_3: StringName = &"CAR_VOICE_WELCOME_3"
const CAR_VOICE_WELCOME_4: StringName = &"CAR_VOICE_WELCOME_4"
const CAR_VOICE_WELCOME_5: StringName = &"CAR_VOICE_WELCOME_5"
const CAR_VOICE_WELCOME_6: StringName = &"CAR_VOICE_WELCOME_6"

# All keys, semicolon-separated: used as hint for inspector dropdowns
const KEY_LIST: String = "BUTTON_CONTINUE,BUTTON_OK,BUTTON_WTF,CAR_VOICE_WELCOME_0,CAR_VOICE_WELCOME_1,CAR_VOICE_WELCOME_2,CAR_VOICE_WELCOME_3,CAR_VOICE_WELCOME_4,CAR_VOICE_WELCOME_5,CAR_VOICE_WELCOME_6"
